name: groot
recipe: wordpress
config:
  webroot: wp
  php: '7.0'

services:
  appserver:
    run_as_root:
      - apt-get update
      - apt-get install zip

    run:
      - cd $LANDO_MOUNT && composer install
      - cd $LANDO_MOUNT && scripts/setup-wordpress.sh

    overrides:
      environment:
        # Pass any non-empty CI envvar from the host into Lando
        # This is so we can force non-interactive mode setting up WP
        CI: ${CI:-''}

  database:
    type: mysql:5.7

  node:
    type: node:10

    globals:
      webpack: "^4.29"
      yarn: "^1.15.2"

    run:
      - yarn

  cypress:
    type: node:10

    globals:
      cypress: "^3.2.0"

    run_as_root:
      - cypress install

    overrides:
      image: 'sitecrafting/lando-cypress-wordpress:latest'

  phpmyadmin:
    type: phpmyadmin:4.7

  mailhog:
    type: mailhog:v1.0.0
    hogfrom:
      - appserver

  docs:
    type: nginx
    ssl: true
    webroot: docs/_book

  gitbook:
    type: node:10

    globals:
      gitbook-cli: "2.3"

    run:
      - gitbook install && gitbook build

tooling:
  install:
    service: appserver
    cmd: '/app/scripts/setup-wordpress.sh'
    description: 'Install and configure WordPress for custom theme dev'

  yarn:
    service: node

  debug:
    service: appserver
    cmd: 'tail -f /app/wp/wp-content/debug.log'
    description: 'Get real-time WP debug log output'

  grunt:
    service: node

  webpack:
    service: node
    cmd: 'node_modules/.bin/webpack'
    description: 'Run arbitrary webpack commands'

  sniff:
    service: appserver
    cmd: 'composer sniff'
    description: 'Run phpcs code sniffer'

  sniff-summary:
    service: appserver
    cmd: 'composer sniff-summary'
    description: 'Summarize phpcs results'

  sniff-fix:
    service: appserver
    cmd: 'composer sniff-fix'
    description: 'Fix coding standards issues that are automatically fixable'

  release:
    service: appserver
    cmd: '/app/scripts/build-release.sh'
    description: 'Build a downloadable release archive of Groot'

  docs:
    service: gitbook
    cmd: '/app/scripts/build-docs.sh /app/docs'
    description: 'Build documentation in _book folder using Gitbook'

  gitbook:
    service: gitbook
    cmd: gitbook
    description: 'Run arbitrary gitbook commands'

proxy:
  appserver:
    - groot.lndo.site

  mailhog:
    - mail.groot.lndo.site
