name: groot
recipe: wordpress
config:
  webroot: wp
  php: '7.0'

services:
  appserver:
    run_as_root:
      # Temporary hack to get a Debian package to install
      # https://github.com/lando/lando/issues/1554
      - echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf
      - echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
      - sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list

      - apt-get update
      - apt-get install zip

    run:
      - cd $LANDO_MOUNT && composer install
      - cd $LANDO_MOUNT && scripts/setup-wordpress.sh

    overrides:
      services:
        environment:
          # Pass any non-empty CI envvar from the host into Lando
          # This is so we can force non-interactive mode setting up WP
          CI: ${CI:-''}

  database:
    type: mysql:5.7

  node:
    type: node:10

    globals:
      yarn: "^1.6"
      parcel: "^1.12"

    run_as_root:
      # hack to get npm to install globals correcly
      - mkdir /.npm && chmod 755 /.npm

    run:
      - yarn

  phpmyadmin:
    type: phpmyadmin:4.7

  mailhog:
    type: mailhog:v1.0.0
    hogfrom:
      - appserver

  docs:
    type: nginx
    ssl: true
    webroot: docs/_book

tooling:
  install:
    service: appserver
    cmd: '/app/scripts/setup-wordpress.sh'
    description: 'Install and configure WordPress for custom theme dev'

  yarn:
    service: node

  debug:
    service: appserver
    cmd: 'tail -f /app/wp/wp-content/debug.log'
    description: 'Get real-time WP debug log output'

  sniff:
    service: appserver
    cmd: 'composer sniff'
    description: 'Run phpcs code sniffer'

  sniff-summary:
    service: appserver
    cmd: 'composer sniff-summary'
    description: 'Summarize phpcs results'

  sniff-fix:
    service: appserver
    cmd: 'composer sniff-fix'
    description: 'Fix coding standards issues that are automatically fixable'

  release:
    service: appserver
    cmd: '/app/scripts/build-release.sh'
    description: 'Build a downloadable release archive of Groot'

  # TODO
  docs:
    service: node
    cmd: '/app/scripts/build-docs.sh /app/docs'
    description: 'Build documentation in _book folder using Gitbook'

  # TODO
  gitbook:
    service: node
    cmd: 'yarn gitbook'
    description: 'Run arbitrary gitbook commands'

  parcel:
    service: node
    cmd: parcel

  build:
    service: node
    cmd: node js/parcel/build.js groot

  node:
    service: node

proxy:
  appserver:
    - groot.lndo.site

  mailhog:
    - mail.groot.lndo.site
