name: groot
recipe: wordpress
config:
  webroot: wp
  php: '8.3'

services:
  appserver:
    run_as_root:
      - apt-get update
      - apt-get install zip

    run:
      - cd $LANDO_MOUNT && composer install
      - cd $LANDO_MOUNT && scripts/setup-wordpress.sh

    overrides:
      environment:
        # Pass any non-empty CI envvar from the host into Lando
        # This is so we can force non-interactive mode setting up WP
        CI: ${CI:-''}

  database:
    type: mysql

  node:
    type: node:22

    globals:
      webpack: "latest"
      yarn: "latest"

    run:
      - yarn

tooling:
  install:
    service: appserver
    cmd: '/app/scripts/setup-wordpress.sh'
    description: 'Install and configure WordPress for custom theme dev'

  yarn:
    service: node

  debug:
    service: appserver
    cmd: 'tail -f /app/wp/wp-content/debug.log'
    description: 'Get real-time WP debug log output'

  webpack:
    service: node
    cmd: 'node_modules/.bin/webpack'
    description: 'Run arbitrary webpack commands'

  # Testing tooling
  unit:
    service: appserver
    cmd: './vendor/bin/phpunit --config phpunit.xml.dist'
    description: 'Run unit tests'

  integration:
      service: appserver
      cmd: './vendor/bin/phpunit --config phpunit-integration.xml.dist'
      description: 'Run integration tests'

  unit-multisite:
      service: appserver
      cmd: './vendor/bin/phpunit --config phpunit-multisite.xml.dist'
      description: 'Run unit tests for multisite'

  integration-multisite:
      service: appserver
      cmd: './vendor/bin/phpunit --config phpunit-integration-multisite.xml.dist'
      description: 'Run integration tests for multisite'

  test:
      service: appserver
      cmd:
          - vendor/bin/phpunit --config phpunit.xml.dist
          - vendor/bin/phpunit --config phpunit-integration.xml.dist
      description: 'Run all unit and integration tests'

  test-multisite:
      service: appserver
      cmd:
          - vendor/bin/phpunit --config phpunit-multisite.xml.dist
          - vendor/bin/phpunit --config phpunit-integration-multisite.xml.dist
      description: 'Run all unit and integration tests in multisite mode'

  sniff:
    service: appserver
    cmd: 'composer sniff'
    description: 'Run phpcs code sniffer'

  sniff-summary:
    service: appserver
    cmd: 'composer sniff-summary'
    description: 'Summarize phpcs results'

  sniff-fix:
    service: appserver
    cmd: 'composer sniff-fix'
    description: 'Fix coding standards issues that are automatically fixable'

  release:
    service: appserver
    cmd: '/app/scripts/build-release.sh'
    description: 'Build a downloadable release archive of Groot'

proxy:
  appserver:
    - groot.lndo.site

